world_positions: # measurements in meters
  names: ['A', 'B', 'C', 'D', 'E','D2'] #, 'C1'] # F is on second row
  pos_x: [0.57, 0.57, 0.57, 0.637, 0.637, 0.637]
  pos_y: [0.33, 0.01, -0.31, 0.33, 0.01, -0.31] # 0.57 and 0.01 is the midpoint that works for both grippers!
  pos_z: [-0.05, -0.05, -0.05, -0.05, -0.05, -0.05]
  
world_objects: # measurements in meters
  names: ['entity', 'position', 'object', 'cube', 'base', 'roof', 'pillar']
  parents: ['', 'entity', 'entity', 'object', 'object', 'object', 'object']
  entity: [0.001, 0.001, 0.001]
  position: [0.05, 0.05, 0.005]
  object: [0.001, 0.001, 0.001]
  cube: [0.065, 0.065, 0.065]
  base: [0.02, 0.085, 0.9]
  roof: [0.03, 0.07, 0.115]
  pillar: [0.035, 0.035, 0.07]
  variance: 0.075