robot_grippers:
  - vacuum_gripper: 'right'
  - claw_gripper: 'left'

world_positions:
  names: ['A', 'B', 'C', 'D']
  pos_x: [0.898, 0.898, 0.898, 1.1]
  pos_y: [-0.434, 0.0, 0.434, 0.0]
  pos_z: [-0.05, -0.05, -0.05, -0.05]
  radius: [0.1,0.1,0.1,0.05]
  
world_objects:
  names: ['cube', 'base', 'roof', 'pillar']
  cube: [10, 10, 5.0]
  base: [13.0, 13.0, 2.5]
  roof: [3.4, 8.0, 5.0]
  pillar: [3.5, 3.5, 7.0]
  variance: [0.075]