robot_grippers:
  - vacuum_gripper: 'right arm'
  - claw_gripper: 'left arm'

world_positions:
  names: ['A', 'B', 'C', 'D']
  pos_x: [0.898, 0.898, 0.898, 1.1]
  pos_y: [-0.434, 0.0, 0.434, 0.0]
  pos_z: [-0.05, -0.05, -0.05, -0.05]
  radius: [0.1,0.1,0.1,0.05]
  
world_objects:
  # Table object dimension ratio
  cube: {'x': 1.0, 'y': 1.0,'z': 1.0}
  tower: {'x': 1.0, 'y': 1.0,'z': 3.0}
  plate: {'x': 1.0, 'y': 1.0,'z': 0.25}
  #- {'name': 'cube', 'dims_ratio': '[1.0,1.0,1.0]'}
  #- {'name': 'rectangle', 'dims_ratio': '[1.0,1.0,2.0]'}
  #- {'name': 'plate', 'dims_ratio': '[1.0,1.0,0.25]'}
  #- {'name': 'tower', 'dims_ratio': '[1.0,1.0,3.0]'}
